# version: '3.8'
# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - CELERY_RESULT_BACKEND=redis://redis:6379/0
#     depends_on:
#       - db
#       - redis

#   db:
#     image: postgres
#     environment:
#       POSTGRES_DB: credit_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"

#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    volumes:
      - .:/app               
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
