# Generated by Django 5.1.3 on 2024-11-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
