# Generated by Django 5.1.3 on 2024-11-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_customer_customer_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="customer",
            new_name="customer_id",
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
