# Generated by Django 5.1.3 on 2024-11-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_customer_loan_customer_id_alter_loan_loan_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="emi_paid_on_time",
            field=models.IntegerField(),
        ),
    ]
